# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - thechosenlan-homebox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f0f67c79785e43c9aea322b84ee6de5b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e8eea0b7270e46d38c82ab4673d22d21 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_f0f67c79785e43c9aea322b84ee6de5b }}/homebox:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'thechosenlan-homebox'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0aadaf1bec68425fa9918d56acf2b6ec }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_f0f67c79785e43c9aea322b84ee6de5b }}/homebox:${{ github.sha }}'