name: Frontend / E2E

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      release:
        required: false
        type: boolean
        default: false

jobs:
  publish:
    name: "Publish Homebox"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build nightly the image
        if: ${{ inputs.release == false }}
        run: |
          docker build --push --no-cache \
            --tag=ghcr.io/OrellBuehler/homebox:${{ inputs.tag }} \
            --build-arg=COMMIT=$(git rev-parse HEAD) \
            --build-arg=BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --platform=linux/amd64,linux/arm64,linux/arm/v7 .

      - name: Build release tagged the image
        if: ${{ inputs.release == true }}
        run: |
          docker build --push --no-cache \
            --tag ghcr.io/OrellBuehler/homebox:nightly \
            --tag ghcr.io/OrellBuehler/homebox:latest \
            --tag ghcr.io/OrellBuehler/homebox:${{ inputs.tag }} \
            --build-arg VERSION=${{ inputs.tag }} \
            --build-arg COMMIT=$(git rev-parse HEAD) \
            --build-arg BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --platform linux/amd64,linux/arm64,linux/arm/v7 .
