name: Build Nightly

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  backend-tests:
    name: "Backend Server Tests"
    uses: OrellBuehler/homebox/.github/workflows/partial-backend.yaml@main

  frontend-tests:
    name: "Frontend and End-to-End Tests"
    uses: OrellBuehler/homebox/.github/workflows/partial-frontend.yaml@main
