name: Build Nightly

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  backend-tests:
    name: "Backend Server Tests"
    uses: OrellBuehler/homebox/.github/workflows/partial-backend.yaml@main

  frontend-tests:
    name: "Frontend and End-to-End Tests"
    uses: OrellBuehler/homebox/.github/workflows/partial-frontend.yaml@main

  publish-nightly:
    name: "Publish Nightly"
    if: github.event_name != 'release'
    needs:
      - backend-tests
      - frontend-tests
    uses: OrellBuehler/homebox/.github/workflows/partial-publish.yaml@main
    with:
      tag: nightly
    secrets:
      GH_TOKEN: ${{ secrets.CR_PAT }}

  publish-tag:
    name: "Publish Tag"
    if: github.event_name == 'release'
    needs:
      - backend-tests
      - frontend-tests
    uses: OrellBuehler/homebox/.github/workflows/partial-publish.yaml@main
    with:
      release: true
      tag: ${{ github.event.release.tag_name }}
    secrets:
      GH_TOKEN: ${{ secrets.CR_PAT }}
